# Generated by Django 5.1.15 on 2026-06-24 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_mechanicprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='mechanicprofile',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude GPS (ex: 48.856613)', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='mechanicprofile',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude GPS (ex: 2.352222)', max_digits=9, null=True),
        ),
    ]
